Resources:
  myDynamoDBTable:    # Logical Id of the resource
    Type: AWS::DynamoDB::Table

    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "destination"
          AttributeType: "S"
        - 
          AttributeName: "nom_de_ligne"
          AttributeType: "S"

      KeySchema:
        - AttributeName: "destination"    # Partition Key
          KeyType: "HASH"
        - AttributeName: "nom_de_ligne"    # Sort Key
          KeyType: "RANGE"

      TableName: "Transport"     

      ProvisionedThroughput:   # Optional, can be skipped
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
