Resources:
  myDynamoDBTable:    # Logical Id of the resource
    Type: AWS::DynamoDB::Table

    Properties:
      AttributeDefinitions:
        - 
          AttributeName: "transportId"
          AttributeType: "S"
        - 
          AttributeName: "destination"
          AttributeType: "S"
        - 
          AttributeName: "nom_de_ligne"
          AttributeType: "S"

      KeySchema:
        - AttributeName: "transportId"
          KeyType: "RANGE"
        - AttributeName: "destination"
          KeyType: "RANGE"
        - AttributeName: "nom_de_ligne"
          KeyType: "RANGE"

      TableName: "Transport"     

      # ProvisionedThroughput:   # Optional, can be skipped
      #   ReadCapacityUnits: 10
      #   WriteCapacityUnits: 10
